name: Update RSS Feed
on:
  workflow_dispatch:
    inputs:
      youtube_url:
        description: 'YouTube Video URL'
        required: true

jobs:
  download-and-convert:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-node-version: '3.10'

    # Bruker pip til å installere yt-dlp stabilt, og apt til ffmpeg
    - name: Install yt-dlp and ffmpeg
      run: |
        python -m pip install --upgrade pip
        pip install yt-dlp
        sudo apt-get update && sudo apt-get install -y ffmpeg

    - name: Download and convert to MP3
      run: |
        mkdir -p mp3
        yt-dlp -x --audio-format mp3 --audio-quality 192k --postprocessor-args "ffmpeg: -ac 2 -ar 44100" -o "mp3/%(title)s.%(ext)s" "${{ github.event.inputs.youtube_url }}"

    - name: Generate RSS Feed
      run: |
        python generate_rss.py

    - name: Commit and Push changes
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
        git add mp3/*.mp3 feed.xml
        git commit -m "Added new episode from YouTube" || echo "No changes to commit"
        git push
